name: chatapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.3
  adaptive_theme: ^3.7.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.5
  country_picker: ^2.0.27
  rounded_loading_button_plus: ^3.0.1
  provider: ^6.1.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  pinput: ^5.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  uuid: ^4.5.1
  flutter_login: ^5.0.0
  flex_color_scheme: ^8.1.1
  intl:
  get: ^4.6.5
  get_storage:
  date_picker_timeline:
  firebase_app_check: ^0.3.2+4
  permission_handler: ^11.4.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.0.0
  swipe_to: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/User/Sample_User_Icon.png
